#ifndef ERROR_H
#define ERROR_H

typedef enum {
    RISK_OK = 0,
    RISK_ERR_INVALID_HEADER,
    RISK_ERR_MISSING_SIGNAL,
    RISK_ERR_DUPLICATE_SIGNAL,
    RISK_ERR_INVALID_ORDER,
    RISK_ERR_OUT_OF_RANGE,
    RISK_ERR_VERSION_MISMATCH
} RiskError;

#endif
